// The real office roster for the 2026 sweepstake (27 players).
export const REAL_PLAYERS = [
  "Abdul Wasey",
  "Abdullah Irshad",
  "Ali Asghar",
  "Ali Sher Aslam",
  "Ehtasham Razzaq",
  "Hamza Ahmad",
  "Jamal",
  "Liaquat Ali",
  "M Kashan Fayyaz",
  "Mohammad Aashir",
  "Mohammed Shahbaz",
  "Muhammad Fahad",
  "Muhammad Shahab Rasheed",
  "Mustaqeem bin Ahmed",
  "Nasir Javed",
  "Roohullah",
  "Sibghat Ullah",
  "Syed Arquam",
  "Tahir",
  "Umer Fayyaz",
  "Usman Ali",
  "Waqar Ahmad Khan",
  "Zain Ali",
  "Syed Usama Bin Tahir",
  "Dan Lindsay",
  "Harry Brown",
  "Hassaan Bin Sajjad",
];
